Repository NewShiftStudio/gour-admin-front, pull requests merged in 2022-10, with the labels that each got.

#90 Метод поиска отредактированных подкатегорий
  src/components/Categories/categories.helper.ts
Labels: bug

#93 Создание/редактирование страниц
  src/view/Pages/List.tsx
Labels: bug

#95 Информационные страницы. TextEditor
  package.json
  src/bootstrap.tsx
  src/components/AboutUs/PagesForm/PagesForm.tsx
  src/components/HookForm/HFTextEditor.tsx
  src/components/UI/TextEditor/TextEditor.tsx
  src/view/Pages/List.tsx
Labels: feat

#94 Выбор участия категории в скидочной программе
  src/@types/dto/category/create.dto.ts
  src/@types/dto/category/update.dto.ts
  src/@types/entities/Category.ts
  src/components/Categories/CreateOrEditForm/CreateOrEditForm.tsx
  src/components/Categories/CreateOrEditForm/types.ts
  src/components/Categories/CreateOrEditModal/CreateOrEditModal.tsx
  src/view/Categories/List.tsx
Labels: feat

#105 Редактирование информационных страниц
  src/constants/tabs.ts
  src/view/Pages/List.tsx
Labels: bug

#103 fix: 🐛 Валидация даты завершения акции
  src/components/Stock/CreateForm/validation.ts
Labels: bug

#102 fix: 🐛 Модальное окно удаления акции
  src/components/Stock/DeleteModal/DeleteModal.tsx
Labels: bug

#100 fix: 🐛 Модалка принятия отзыва
  src/components/ConfirmReviewModal/ConfirmReviewModal.style.ts
  src/components/ConfirmReviewModal/ConfirmReviewModal.tsx
Labels: bug

#99 fix: 🐛 Положение текста ошибки при создании акции
  src/components/Stock/CreateForm/CreateForm.tsx
Labels: bug

#104 feat: 🎸 TextEditor в описании продукта
  src/components/Product/BasicSettingsForm/BasicSettingsForm.tsx
Labels: feat

#97 Страница подтверждения комментариев
  src/@types/entities/ProductGrade.ts
  src/components/ConfirmReviewModal/ConfirmReviewModal.styles.ts
  src/components/ConfirmReviewModal/ConfirmReviewModal.tsx
  src/components/Review/review.helper.ts
  src/view/Reviews/List.tsx
Labels: bug

#106 fix: 🐛 chapter links
  src/@types/dto/auth/signin.dto.ts
  src/components/Auth/ForgotPasswordForm/ForgotPasswordForm.tsx
  src/components/Auth/SignInForm/SignInForm.tsx
  src/components/Auth/SignInForm/validation.ts
  src/components/Product/Table/Table.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Stock/Table/Table.tsx
  src/components/UI/Button/Button.tsx
  src/components/UI/IconButton/IconButton.tsx
  src/components/UI/Link/Link.tsx
  src/layouts/Private.tsx
  src/view/Products/List.tsx
  src/view/Stocks/List.tsx
Labels: bug

#110 fix: 🐛 удаление пользователей и их роли
  src/api/authApi.ts
  src/api/clientRoleApi.ts
  src/api/commonApi.ts
  src/api/userApi.ts
  src/api/userRoleApi.ts
  src/components/Auth/SignInForm/SignInForm.tsx
  src/components/Categories/CreateOrEditForm/CreateOrEditForm.styles.ts
  src/components/Categories/CreateOrEditForm/CreateOrEditForm.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Users/AddCoinsModal/AddCoinsModal.tsx
  src/components/Users/AddCoinsModal/validation.ts
  src/components/Users/CreateForm/CreateForm.styles.ts
  src/components/Users/CreateForm/CreateForm.tsx
  src/components/Users/CreateForm/validation.ts
  src/components/Users/Table/Table.styles.ts
  src/components/Users/Table/Table.tsx
  src/constants/routes.ts
  src/constants/users/roles.ts
  src/layouts/Private.tsx
  src/store/rootReducer.ts
  src/themes.ts
  src/types/dto/add-cheesecoins.dto.ts
  src/types/dto/add-coins.dto.ts
  src/types/dto/auth/signup-without-password.dto.ts
  src/types/dto/user/create.dto.ts
  src/types/entities/Base.ts
  src/types/entities/Client.ts
  src/types/entities/ClientRole.ts
  src/types/entities/ProductGrade.ts
  src/types/entities/User.ts
  src/types/entities/UserRole.ts
  src/types/index.d.ts
  src/view/Auth/SignIn.tsx
  src/view/Products/Create.tsx
  src/view/Users/Create.tsx
  src/view/Users/List.tsx
Labels: fix
